set(_CATKIN_CURRENT_PACKAGE "urg_c")
set(urg_c_VERSION "1.0.405")
set(urg_c_MAINTAINER "Chad Rockey <chadrockey@gmail.com>, Tony Baltovski <tony.baltovski@gmail.com>")
set(urg_c_PACKAGE_FORMAT "1")
set(urg_c_BUILD_DEPENDS )
set(urg_c_BUILD_EXPORT_DEPENDS )
set(urg_c_BUILDTOOL_DEPENDS "catkin")
set(urg_c_BUILDTOOL_EXPORT_DEPENDS )
set(urg_c_EXEC_DEPENDS )
set(urg_c_RUN_DEPENDS )
set(urg_c_TEST_DEPENDS )
set(urg_c_DOC_DEPENDS )
set(urg_c_URL_WEBSITE "http://sourceforge.net/projects/urgwidget/")
set(urg_c_URL_BUGTRACKER "https://github.com/ros-drivers/urg_c/issues")
set(urg_c_URL_REPOSITORY "https://github.com/ros-drivers/urg_c")
set(urg_c_DEPRECATED "")