<?xml version="1.0"?>
<robot name="caster_wheels" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>

    <!-- Front caster definition -->
    <link name="${tf_prefix}/front_caster_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <xacro:sphere_inertia mass="${caster_link_mass}" radius="${caster_link_radius}"/>
        </inertial>
    </link>

    <joint name="${tf_prefix}/front_caster_link_joint" type="fixed">
        <parent link="${tf_prefix}/chassis_link"/>
        <child link="${tf_prefix}/front_caster_link"/>
        <origin rpy="0 0 0" xyz="${casters_separation / 2.0} 0 ${caster_vertical_offset}"/>
    </joint>

    <gazebo reference="${tf_prefix}/front_caster_link">
        <mu1 value="0.3"/>
        <mu2 value="0.3"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
    </gazebo>

    <!-- Back caster definition -->
    <link name="${tf_prefix}/back_caster_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/> 
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <xacro:sphere_inertia mass="${caster_link_mass}" radius="${caster_link_radius}"/>
        </inertial>
    </link>

    <joint name="${tf_prefix}/back_caster_link_joint" type="fixed">
        <parent link="${tf_prefix}/chassis_link"/>
        <child link="${tf_prefix}/back_caster_link"/>
        <origin rpy="0 0 0" xyz="-${casters_separation / 2.0} 0 ${caster_vertical_offset}"/>
    </joint>

    <gazebo reference="${tf_prefix}/back_caster_link">
        <mu1 value="0.3"/>
        <mu2 value="0.3"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
    </gazebo>
</robot>

