<?xml version="1.0"?>
<robot name="caster_wheels" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="tf_prefix" default="caffeine"/>

    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>

    <!-- Front caster definition -->
    <link name="$(arg tf_prefix)/front_caster_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/front_caster.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/front_caster.dae"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <xacro:caster_link_inertia/>
        </inertial>
    </link>

    <!-- NOTE: using a fixed joint prevents Caffeine spawning tipped over -->
    <joint name="$(arg tf_prefix)/front_caster_link_joint" type="fixed">
        <!-- <axis xyz="0 0 1"/> -->
        <parent link="$(arg tf_prefix)/chassis_link"/>
        <child link="$(arg tf_prefix)/front_caster_link"/>
        <origin rpy="0 0 0" xyz="${casters_separation / 2.0} 0 ${caster_vertical_offset}"/>
    </joint>

    <!-- Back caster definition -->
    <link name="$(arg tf_prefix)/back_caster_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/back_caster.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/back_caster.dae"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <xacro:caster_link_inertia/>
        </inertial>
    </link>

    <!-- NOTE: using a fixed joint prevents Caffeine spawning tipped over -->
    <joint name="$(arg tf_prefix)/back_caster_link_joint" type="fixed">
        <!-- <axis xyz="0 0 1"/> -->
        <parent link="$(arg tf_prefix)/chassis_link"/>
        <child link="$(arg tf_prefix)/back_caster_link"/>
        <origin rpy="0 0 0" xyz="-${casters_separation / 2.0} 0 ${caster_vertical_offset}"/>
    </joint>

    <!-- Front caster wheel definition -->
    <link name="$(arg tf_prefix)/front_caster_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/front_caster_wheel.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/front_caster_wheel.dae"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_wheel_mass}"/>
            <xacro:caster_wheel_inertia/>
        </inertial>

    </link>

    <joint name="$(arg tf_prefix)/front_caster_wheel_joint" type="continuous">
        <parent link="$(arg tf_prefix)/front_caster_link"/>
        <child link="$(arg tf_prefix)/front_caster_wheel"/>
        <origin rpy="0 0 0" xyz="${caster_link_to_wheel_dist_x} 0 ${caster_link_to_wheel_dist_z}"/>

        <axis xyz="0 1 0"/>
    </joint>

    <!-- Back caster wheel definition -->
    <link name="$(arg tf_prefix)/back_caster_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/back_caster_wheel.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/back_caster_wheel.dae"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${caster_wheel_mass}"/>
            <xacro:caster_wheel_inertia/>
        </inertial>
    </link>
        
    <joint name="$(arg tf_prefix)/back_caster_wheel_joint" type="continuous">
        <parent link="$(arg tf_prefix)/back_caster_link"/>
        <child link="$(arg tf_prefix)/back_caster_wheel"/>
        <origin rpy="0 0 0" xyz="-${caster_link_to_wheel_dist_x} 0 ${caster_link_to_wheel_dist_z}"/>

        <axis xyz="0 1 0"/>
    </joint>


</robot>

