<?xml version="1.0"?>
<robot name="caffeine_constants" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Caffeine -->
    <xacro:property name="robotNamespace" value="caffeine"/>
    <xacro:property name="tf_prefix" value="caffeine"/>

    <!-- Drivebase -->
   <xacro:property name="base_length" value="1.268"/>
   <xacro:property name="base_width" value="0.764"/>
   <xacro:property name="base_height" value="0.01"/>

    <!-- Chassis --> 
    <xacro:property name="chassis_to_base_link_dist" value="0.501747"/>
    <xacro:property name="chassis_to_stand_link_dist" value="0.713459"/>

    <xacro:property name="chassis_link_mass" value="33.9"/>

    <!-- Casters -->
    <xacro:property name="caster_link_mass" value="0.5"/>
    
    <xacro:property name="casters_separation" value="1.12"/>
    <xacro:property name="caster_vertical_offset" value="-0.619167561"/>

    <xacro:property name="caster_wheel_mass" value="0.7"/>

    <xacro:property name="caster_link_to_wheel_dist_x" value="0.03621719"/>
    <xacro:property name="caster_link_to_wheel_dist_z" value="-0.04361749"/>

    <!-- Wheels -->
    <!-- TODO: Update acceleration and torque parameters when known -->
    <xacro:property name="wheel_vertical_offset" value="-0.61759696"/>
    
    <xacro:property name="wheel_left_joint" value="left_wheel_joint"/>
    <xacro:property name="wheel_right_joint" value="right_wheel_joint"/>

    <xacro:property name="wheels_separation" value="0.875"/>
    <xacro:property name="wheel_diameter" value="0.25"/>

    <xacro:property name="wheel_acceleration" value="1.0"/>
    <xacro:property name="wheel_torque" value="20"/>

    <xacro:property name="wheel_mass" value="4.45"/>

    <!-- Gazebo Motor -->
    <xacro:property name="diff_drive_update_rate" value="30.0"/>

    <xacro:property name="diff_drive_commandTopic" value="cmd_vel"/>
    <xacro:property name="diff_drive_odometryTopic" value="odom"/>

    <xacro:property name="diff_drive_odometryFrame" value="odom"/>
    <xacro:property name="diff_drive_robotBaseFrame" value="base_link"/>

    <xacro:property name="diff_drive_odometrySource" value="encoder"/>

    <xacro:property name="diff_drive_publishWheelTF" value="false"/>
    <xacro:property name="diff_drive_publishOdomTF" value="true"/>
    <xacro:property name="diff_drive_publishTf" value="true"/>
    <xacro:property name="diff_drive_publishWheelJointState" value="true"/>

    <xacro:property name="diff_drive_legacymode" value="false"/>
    <xacro:property name="diff_drive_rosDebugLevel" value="na"/>

    <!-- Hokuyo 2D LIDAR sensor -->
    <xacro:property name="laser_visualize" value="false"/>
    <xacro:property name="laser_update_rate" value="10"/>

    <xacro:property name="laser_horizontal_samples" value="1080"/>
    <xacro:property name="laser_horizontal_resolution" value="1"/>
    <xacro:property name="laser_field_of_view" value="270"/>
    <xacro:property name="laser_horizontal_min_angle" value="${-0.5*laser_field_of_view*pi/180}"/>
    <xacro:property name="laser_horizontal_max_angle" value="${0.5*laser_field_of_view*pi/180}"/>

    <xacro:property name="laser_range_min" value="0.06"/>
    <xacro:property name="laser_range_max" value="4.095"/>
    <xacro:property name="laser_resolution_angle" value="0.36"/> 
    <xacro:property name="laser_range_resolution" value="${laser_resolution_angle*pi/180}"/>

    <xacro:property name="laser_noise_type" value="gaussian"/>
    <xacro:property name="laser_noise_mean" value="0.0"/>
    <xacro:property name="laser_noise_stddev" value="0.01/3"/>

    <xacro:property name="laser_topicName" value="scan"/>
    <xacro:property name="laser_frameName" value="base_laser"/>

    <xacro:property name="laser_length" value="0.05"/>
    <xacro:property name="laser_width" value="0.05"/>
    <xacro:property name="laser_height" value="0.07"/>
    <xacro:property name="laser_mass" value="0.16"/> 

    <xacro:property name="laser_x_dist" value="${base_length/2 - 2*laser_length}"/>
    <xacro:property name="laser_z_dist" value="${laser_height/2}"/>  
</robot>

