<?xml version="1.0"?>
<robot name="stand_link" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>
    
    <!-- Stand link; this is a dummy link that is used to make camera placement and other sensors on the stand more convenient -->
    <!-- Stand link definition. Note: purposely left blank -->
    <link name="${tf_prefix}/stand_link">
    </link>

    <!-- GPS -->
    <link name="${tf_prefix}/gps_link">
        <inertial>
            <mass value="${gps_mass}"/>
            <xacro:cylinder_inertia mass="${gps_mass}" length="${gps_length}" radius="${gps_diam / 2.0}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gps_length}" radius="${gps_diam / 2.0}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gps_length}" radius="${gps_diam / 2.0}"/>
            </geometry>
        </collision>
    </link>

    <!-- GPS: attach gps_link to stand_link -->
    <joint name="${tf_prefix}/gps_joint" type="fixed">
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/gps_link"/>
        <origin xyz="0 0 ${(gps_length + phidget_height) / 2.0}" rpy="0 0 0"/>
    </joint>

    <!-- IMU -->
    <link name="${tf_prefix}/imu_link">
        <inertial>
            <mass value="${phidget_mass}"/>
            <xacro:box_inertia mass="${phidget_mass}" length="${phidget_length}" width="${phidget_width}" height="${phidget_height}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- IMU: attach imu_link to stand_link -->
    <joint name="${tf_prefix}/base_link_to_imu_link" type="fixed">
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>

