<?xml version="1.0"?>
<robot name="stand_link" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>
    
    <!-- Stand link; this is a dummy link that is used to make camera placement and other sensors on the stand more convenient -->
    <!-- Stand link definition. Note: purposely left blank -->
    <link name="stand_link">
    </link> 

    <!-- ZED Camera -->
    <link name="zed_camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <!-- TODO: should be using the mesh but couldn't get it to work -->
            <geometry>
            <box size="${ZED_camera_width} ${ZED_camera_length} ${ZED_camera_height}"/>
            </geometry>
        </visual>  
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${ZED_camera_width} ${ZED_camera_length} ${ZED_camera_height}"/>
            </geometry>
        </collision>
        <inertial>
            <xacro:box_inertia mass="${ZED_camera_mass}" length="${ZED_camera_length}" width="${ZED_camera_width}" height="${ZED_camera_height}"/>
            <mass value="${ZED_camera_mass}"/>
        </inertial>
    </link>
    <joint name="zed_camera_joint" type="fixed">
        <parent link="stand_link"/>
        <child link="zed_camera_link"/>
        <origin xyz="${stand_length/2} 0 ${stand_height + ZED_camera_height}" rpy="0 0 0"/>
    </joint>

    <!-- ZED camera lenses -->
    <!-- NOTE: I'm only defining one and not visually showing any-->
    <!-- I only need one for purposes of using the plugin -->
    <!-- TODO: check if it's fine to call the left lense camera_link (rtabmap doesn't specify whether it wants the lense frame or the camera frame itself) -->
    <link name="camera_link"> 
        <!-- Inertial tag here to ensure that link does not phase through robot-->
        <inertial>
            <mass value="0.0001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.00001"/>
        </inertial>
    </link>
    <joint name="camera_link_joint" type="fixed">
        <origin xyz="${ZED_camera_length/2.0} 0 0" rpy="0 0 0"/>
        <parent link="zed_camera_link"/>
        <child link="camera_link"/>
    </joint>

    <!-- Generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames so that ros and opencv can operate on the camera frame correctly -->
    <link name="zed_camera_link_optical">
    </link>
    <joint name="zed_camera_link_optical_joint" type="fixed">
        <!-- Transform b/w standard and optical frame -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="zed_camera_link"/>
        <child link="zed_camera_link_optical"/>
    </joint>    

</robot>

