set(_CATKIN_CURRENT_PACKAGE "urg_node")
set(urg_node_VERSION "0.1.16")
set(urg_node_MAINTAINER "Tony Baltovski <tony.baltovski@gmail.com>")
set(urg_node_PACKAGE_FORMAT "2")
set(urg_node_BUILD_DEPENDS "diagnostic_updater" "dynamic_reconfigure" "laser_proc" "message_generation" "nodelet" "rosconsole" "roscpp" "sensor_msgs" "std_msgs" "std_srvs" "tf" "urg_c")
set(urg_node_BUILD_EXPORT_DEPENDS "diagnostic_updater" "dynamic_reconfigure" "laser_proc" "message_generation" "nodelet" "rosconsole" "roscpp" "sensor_msgs" "std_msgs" "std_srvs" "tf" "urg_c")
set(urg_node_BUILDTOOL_DEPENDS "catkin")
set(urg_node_BUILDTOOL_EXPORT_DEPENDS )
set(urg_node_EXEC_DEPENDS "message_runtime" "xacro" "diagnostic_updater" "dynamic_reconfigure" "laser_proc" "message_generation" "nodelet" "rosconsole" "roscpp" "sensor_msgs" "std_msgs" "std_srvs" "tf" "urg_c")
set(urg_node_RUN_DEPENDS "message_runtime" "xacro" "diagnostic_updater" "dynamic_reconfigure" "laser_proc" "message_generation" "nodelet" "rosconsole" "roscpp" "sensor_msgs" "std_msgs" "std_srvs" "tf" "urg_c")
set(urg_node_TEST_DEPENDS "roslint" "roslaunch")
set(urg_node_DOC_DEPENDS )
set(urg_node_URL_WEBSITE "http://ros.org/wiki/urg_node")
set(urg_node_URL_BUGTRACKER "https://github.com/ros-drivers/urg_node/issues")
set(urg_node_URL_REPOSITORY "https://github.com/ros-drivers/urg_node")
set(urg_node_DEPRECATED "")