set(_CATKIN_CURRENT_PACKAGE "laser_proc")
set(laser_proc_VERSION "0.1.6")
set(laser_proc_MAINTAINER "Chad Rockey <chadrockey@willowgarage.com>")
set(laser_proc_PACKAGE_FORMAT "1")
set(laser_proc_BUILD_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "pluginlib" "nodelet")
set(laser_proc_BUILD_EXPORT_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "pluginlib" "nodelet")
set(laser_proc_BUILDTOOL_DEPENDS "catkin")
set(laser_proc_BUILDTOOL_EXPORT_DEPENDS )
set(laser_proc_EXEC_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "pluginlib" "nodelet")
set(laser_proc_RUN_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "pluginlib" "nodelet")
set(laser_proc_TEST_DEPENDS )
set(laser_proc_DOC_DEPENDS )
set(laser_proc_URL_WEBSITE "http://ros.org/wiki/laser_proc")
set(laser_proc_URL_BUGTRACKER "https://github.com/ros-perception/laser_proc/issues")
set(laser_proc_URL_REPOSITORY "https://github.com/ros-perception/laser_proce")
set(laser_proc_DEPRECATED "")