<?xml version="1.0"?>
<robot name="caffeine" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/plugins.gazebo.xacro"/>

    <!-- base_link: origin of the robot; located in the middle, on the top of the base plate -->
    <link name="base_link"/>

    <!-- chassis_link: geometric center of the robot; used as the parent in which all other links connect to -->
    <xacro:include filename="$(find description)/urdf/chassis_link.urdf.xacro"/>

    <!-- stand_link: origin for anything on the stand; located in the middle, on the top of the stand plate -->
    <xacro:include filename="$(find description)/urdf/stand_link.urdf.xacro"/>

    <!-- wheels: associated to wheels that can be moved by a motor -->
    <xacro:include filename="$(find description)/urdf/side_wheels.urdf.xacro"/>

    <!-- wheels: front and back casters -->
    <xacro:include filename="$(find description)/urdf/casters.urdf.xacro"/>

    <!-- base_laser: LIDAR at front of Caffeine -->
    <link name="base_laser">
        <inertial>
            <mass value="${laser_mass}"/>
            <xacro:box_inertia mass="${laser_mass}" length="${laser_length}" width="${laser_width}" height="${laser_height}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://description/urdf/meshes/hokuyo.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://description//urdf/meshes/hokuyo.dae"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_laser"/>
        <origin xyz="${laser_x_dist} 0 ${laser_z_dist}" rpy="0 0 0"/>
    </joint>
    <!-- IMU (IS CONNECTED TO BASE LINK) -->
    <link name="imu_link">
        <inertial>
            <mass value="${phidget_mass}"/>
            <xacro:box_inertia mass="${phidget_mass}" length="${phidget_length}" width="${phidget_width}" height="${phidget_height}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="base_link_to_imu_link" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${imu_x_dist} ${imu_y_dist} ${imu_z_dist}" rpy="0 0 0"/>
    </joint> 

    <!-- Second upper lidar -->

    <link name="upper_laser">
        <inertial>
            <mass value="${laser_mass}"/>
            <xacro:box_inertia mass="${laser_mass}" length="${laser_length}" width="${laser_width}" height="${laser_height}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://description/urdf/meshes/hokuyo.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://description//urdf/meshes/hokuyo.dae"/>
            </geometry>
        </collision>
    </link>

    <joint name="upper_laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="upper_laser"/>
        <origin xyz="${laser_x_dist} 0 ${laser_z_dist+distance_to_second_lidar}" rpy="0 0 0"/>
    </joint>

</robot>
