<?xml version="1.0"?>
<robot name="stand_link" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>
    
    <!-- Stand link; this is a dummy link that is used to make camera placement and other sensors on the stand more convenient -->
    <!-- Stand link definition. Note: purposely left blank -->
    <link name="${tf_prefix}/stand_link"/> 
    <joint name="${tf_prefix}/stand_link_joint" type="fixed">
        <parent link="${tf_prefix}/chassis_link"/>
        <child link="${tf_prefix}/stand_link"/>
        <origin xyz="0 0 ${chassis_to_stand_link_dist}" rpy="0 0 0" />
    </joint>

    <!-- ZED Camera -->
    <link name="${tf_prefix}/zed_camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${ZED_camera_width} ${ZED_camera_length} ${ZED_camera_height}"/>
            </geometry>
        </visual>  
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${ZED_camera_width} ${ZED_camera_length} ${ZED_camera_height}"/>
            </geometry>
        </collision>
        <inertial>
            <xacro:box_inertia mass="${ZED_camera_mass}" length="${ZED_camera_length}" width="${ZED_camera_width}" height="${ZED_camera_height}"/>
            <mass value="${ZED_camera_mass}"/>
        </inertial>
    </link>
    <joint name="${tf_prefix}/zed_camera_joint" type="fixed">
        <origin xyz="${stand_length/2 - ZED_camera_width} 0 ${ZED_camera_height / 2.0}" rpy="0 ${ZED_camera_pitch} 0"/>
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/zed_camera_link"/>
    </joint>

    <!-- GPS -->
    <link name="${tf_prefix}/gps_link">
        <inertial>
            <mass value="${gps_mass}"/>
            <xacro:cylinder_inertia mass="${gps_mass}" length="${gps_length}" radius="${gps_diam / 2.0}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gps_length}" radius="${gps_diam / 2.0}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gps_length}" radius="${gps_diam / 2.0}"/>
            </geometry>
        </collision>
    </link>

    <!-- GPS: attach gps_link to stand_link -->
    <joint name="${tf_prefix}/gps_joint" type="fixed">
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/gps_link"/>
        <origin xyz="0 0 ${(gps_length + phidget_height) / 2.0}" rpy="0 0 0"/>
    </joint>

    <!-- IMU -->
    <link name="${tf_prefix}/imu_link">
        <inertial>
            <mass value="${phidget_mass}"/>
            <xacro:box_inertia mass="${phidget_mass}" length="${phidget_length}" width="${phidget_width}" height="${phidget_height}"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${phidget_length} ${phidget_width} ${phidget_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- IMU: attach imu_link to stand_link -->
    <joint name="${tf_prefix}/base_link_to_imu_link" type="fixed">
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- ZED camera lenses -->
    <!-- NOTE: I'm only defining one and not visually showing any-->
    <!-- I only need one for purposes of using the plugin -->
    <!-- TODO: check if it's fine to call the left lense camera_link (rtabmap doesn't specify whether it wants the lense frame or the camera frame itself) -->
    <link name="${tf_prefix}/camera_link"> 
        <!-- Inertial tag here to ensure that link does not phase through robot-->
        <inertial>
            <mass value="0.0001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.00001"/>
        </inertial>
    </link>
    <joint name="${tf_prefix}/zed_camera_link_joint" type="fixed">
        <origin xyz="${ZED_camera_length/2.0} 0 0" rpy="0 0 0"/>
        <parent link="${tf_prefix}/zed_camera_link"/>
        <child link="${tf_prefix}/camera_link"/>
    </joint>

    <!-- Generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames so that ros and opencv can operate on the camera frame correctly -->
    <link name="${tf_prefix}/zed_camera_link_optical"/>

    <joint name="${tf_prefix}/zed_camera_link_optical_joint" type="fixed">
        <!-- Transform b/w standard and optical frame -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="${tf_prefix}/zed_camera_link"/>
        <child link="${tf_prefix}/zed_camera_link_optical"/>
    </joint>

</robot>
